html_add = """
            <!-- Planner View -->
            <div id="view-planner" class="tab-view" style="display: none;">
                <div class="dashboard-grid">
                    
                    <!-- Top section: Season Alert & Crop Selector -->
                    <section class="card full-width" style="display: flex; justify-content: space-between; align-items: center; background: linear-gradient(135deg, rgba(16, 185, 129, 0.1), rgba(6, 95, 70, 0.1)); border: 1px solid var(--primary-color);">
                        <div id="season-alert" style="flex: 1;">
                            <h3 style="color: var(--primary-color); margin-bottom: 0.5rem;"><i data-lucide="sun"></i> Season Radar</h3>
                            <p id="season-alert-text" style="font-size: 1.1rem; color: var(--text-color);">Detecting next season...</p>
                        </div>
                        <div style="flex: 1; text-align: right;">
                            <label for="planner-crop-select" style="font-weight: 500; margin-right: 1rem;">Select Crop to Plan:</label>
                            <select id="planner-crop-select" class="theme-select" style="padding: 0.5rem 1rem; border-radius: 8px; border: 1px solid rgba(16, 185, 129, 0.3); background: rgba(15, 23, 42, 0.8); color: var(--text-color); font-size: 1rem;" onchange="updatePlanner()">
                                <!-- Populated by JS -->
                            </select>
                        </div>
                    </section>
                    
                    <!-- Left: Seasonal Timeline -->
                    <section class="card" style="grid-column: span 2;">
                        <div class="card-header">
                            <i data-lucide="calendar-days"></i>
                            <h3>Seasonal Timeline</h3>
                        </div>
                        <div class="timeline-container">
                            <div class="timeline-grid" id="timelineGrid">
                                <!-- Generated by JS -->
                            </div>
                            <div class="timeline-legend" style="display: flex; gap: 1rem; margin-top: 1.5rem; justify-content: center; font-size: 0.9rem;">
                                <div style="display: flex; align-items: center; gap: 0.5rem;"><span style="width: 12px; height: 12px; background: #3b82f6; border-radius: 3px;"></span> Sowing</div>
                                <div style="display: flex; align-items: center; gap: 0.5rem;"><span style="width: 12px; height: 12px; background: #f59e0b; border-radius: 3px;"></span> Harvesting</div>
                            </div>
                        </div>
                    </section>
                    
                    <!-- Right: Farm School -->
                    <section class="card" style="grid-column: span 1;">
                        <div class="card-header">
                            <i data-lucide="graduation-cap"></i>
                            <h3>Farm School</h3>
                        </div>
                        <div id="farmSchoolContent" style="display: flex; flex-direction: column; gap: 1rem; margin-top: 1rem;">
                            <!-- Populated by JS -->
                            <p style="color: var(--text-muted); font-style: italic;">Select a crop to view the educational guide.</p>
                        </div>
                    </section>
                </div>
            </div>

</main>
"""

with open('frontend/index.html', 'r', encoding='utf-8') as f:
    code = f.read()

# Remove the duplicate History View
history_block = """<!-- History View -->
            <div id="view-history" class="tab-view" style="display: none;">
                <div class="dashboard-grid">
                    <section class="card">
                        <div class="card-header">
                            <i data-lucide="plus-circle"></i>
                            <h3>Log New Yield</h3>
                        </div>
                        <form id="yieldForm" onsubmit="submitYield(event)" style="display: flex; flex-direction: column; gap: 1rem;">
                            <div class="control-group">
                                <label>Crop</label>
                                <input type="text" id="yieldCrop" required style="padding: 0.75rem; background: var(--bg-card); border: 1px solid var(--border); color: white; border-radius: 8px;">
                            </div>
                            <div class="control-group">
                                <label>Season</label>
                                <select id="yieldSeason" style="padding: 0.75rem;">
                                    <option value="Kharif">Kharif</option>
                                    <option value="Rabi">Rabi</option>
                                    <option value="Zaid">Zaid</option>
                                </select>
                            </div>
                            <div class="control-group">
                                <label>Yield Amount (Quintals)</label>
                                <input type="number" id="yieldAmount" required min="1" style="padding: 0.75rem; background: var(--bg-card); border: 1px solid var(--border); color: white; border-radius: 8px;">
                            </div>
                            <button type="submit" class="btn-primary" style="margin-top: 1rem;"><i data-lucide="save"></i> Save Record</button>
                        </form>
                    </section>
                    
                    <section class="card">
                        <div class="card-header">
                            <i data-lucide="bar-chart-2"></i>
                            <h3>Past Yield Records</h3>
                        </div>
                        <div id="historyList" style="display: flex; flex-direction: column; gap: 1rem;">
                            <!-- Populated by JS -->
                        </div>
                    </section>
                </div>
            </div>
"""

# Try to remove duplicate if it exists exactly
if code.count(history_block) > 1:
    code = code.replace(history_block, "", 1) # replace first occurrence with empty

if 'view-planner' not in code:
    code = code.replace('</main>', html_add)

with open('frontend/index.html', 'w', encoding='utf-8') as f:
    f.write(code)
print("Updated index.html")
